services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres           # FIXED
      POSTGRES_PASSWORD: avyuXYZ@07
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_backend
    restart: always
    depends_on:
      - postgres
    environment:
      SECRET_KEY: llm0726shaavy20002002
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      ADMIN_USERNAME: eminent0267@gmail.com
      ADMIN_PASSWORD: admin0726@
      GROQ_API_KEY: ${GROQ_API_KEY}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres                # MUST MATCH ABOVE
      POSTGRES_PASSWORD: avyuXYZ@07
      POSTGRES_HOST: postgres                # FIXED
      POSTGRES_PORT: 5432                    # INTERNAL PORT
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend

volumes:
  pgdata:
